# -*- mode: python -*-

Import('env')

env = env.Clone()

timeZoneEnv = env.Clone()
timeZoneEnv.Library(
    target='timezone_decorator',
    source=[
        'timezone_decorator.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context',
    ]
)

timeZoneEnv.Library(
    target='init_timezone_data',
    source=[
        'init_timezone_data.cpp'
    ],
    LIBDEPS=[
        'timezone_decorator',
        '$BUILD_DIR/mongo/db/server_options_core',
    ]
)
